prometheus:
  prometheusSpec:
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}  
  service:
    type: NodePort
    nodePort: 30001
grafana:
 service:
    type: NodePort
    nodePort: 30000


