// Auto-generated by the Load Impact converter

import "./libs/shim/core.js";

export let options = {
  stages: [
    { duration: '4m', target: 30 },
    { duration: '4m', target: 45 },
    { duration: '4m', target: 60 },
  ],
  userAgent: 'MyK6UserAgentString/1.0',
};

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options
});

export default function() {
  postman[Request]({
    name: "getUser",
    id: "8814f6ae-f7b5-4751-8c26-d202f6abfc90",
    method: "GET",
    address:
      "http://arch.homework:80/otus/shmakov.a/api/user/8814f6ae-f7b5-4751-8c26-d202f6abfc90"
  });

  postman[Request]({
    name: "updateUser",
    id: "8814f6ae-f7b5-4751-8c26-d202f6abfc90",
    method: "PUT",
    address:
      "http://arch.homework:80/otus/shmakov.a/api/user/8814f6ae-f7b5-4751-8c26-d202f6abfc90",
    data:
      '{\r\n  "userId": "8814f6ae-f7b5-4751-8c26-d202f6abfc90",\r\n  "userName": "User2",\r\n  "firstName": "OTUSNew",\r\n  "lastName": "Kubernetovich",\r\n  "email": "otus@otus.ru",\r\n  "phone": "+9123456789"\r\n}'
  });

  postman[Request]({
    name: "deleteUser",
    id: "d4bdc7d4-0a53-4c50-983a-d0a008af6d3a",
    method: "DELETE",
    address:
      "http://arch.homework:80/otus/shmakov.a/api/user/9d6b0ba4-f976-4ab9-91eb-08a21c5f1b7a"
  });
}
