controller:
  kind: DaemonSet

  reportNodeInternalIp: true

  hostPort:
    enabled: true
    ports:
      http: 80
      https: 443
  
  metrics:
    enabled: true
    prometheus.io/scrape: "true"
    prometheus.io/port: "10254"