
apiVersion: v1
kind: ConfigMap
metadata:
  name: homework-config
data:
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  BILLING_SERVICE_URL: "http://billing-service.default.svc.cluster.local:15010"
  appsettings.json: |-
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "System": "Information",
          "Microsoft": "Information"
        }
      }
    }

---
apiVersion: v1
kind: Secret
metadata:
  name: homework-secret
data:
  ESHOP_DATABASE_URI: SG9zdD1wb3N0Z3JlcztEYXRhYmFzZT1vdHVzX2VzaG9wO1VzZXJuYW1lPXBvc3RncmVzO1Bhc3N3b3JkPXRjXzEyMzQ1Ng==
  BILLING_DATABASE_URI: SG9zdD1wb3N0Z3JlcztEYXRhYmFzZT1vdHVzX2JpbGxpbmc7VXNlcm5hbWU9cG9zdGdyZXM7UGFzc3dvcmQ9dGNfMTIzNDU2
