
apiVersion: v1
kind: ConfigMap
metadata:
  name: homework-config
data:
   appsettings.json: |-
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "System": "Error",
          "Microsoft": "Error"
        }
      }
    } 

---
apiVersion: v1
kind: Secret
metadata:
  name: homework-secret
data:
  DATABASE_URI: SG9zdD1wb3N0Z3JlcztEYXRhYmFzZT1vdHVzaG9tZXdvcms7VXNlcm5hbWU9cG9zdGdyZXM7UGFzc3dvcmQ9dGNfMTIzNDU2
