### eshop api
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homework
spec:
  replicas: 2
  selector:
    matchLabels:
      app: homeworkapp
  template:
    metadata:
      labels:
        app: homeworkapp
    spec:
      initContainers:
        - name: check-db-ready
          image: postgres:latest
          env:
            - name: POSTGRES_HOST
              valueFrom:  
                configMapKeyRef: 
                  name: homework-config
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:  
                configMapKeyRef: 
                  name: homework-config
                  key: POSTGRES_PORT
          command:
            - sh
            - "-c"
            - |
              until pg_isready -h $POSTGRES_HOST -p $POSTGRES_PORT;
              do echo waiting for database; sleep 2; done;
      containers:
      - name: homeworkapp
        image: alexcei88/otushomeworkeshop
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"          
        ports:
          - containerPort: 80
        env:
          - name: "ConnectionStrings__DefaultConnection"
            valueFrom:
              secretKeyRef:
                name: homework-secret
                key: ESHOP_DATABASE_URI
          - name: "BillingService__Url"
            valueFrom:
               configMapKeyRef: 
                  name: homework-config
                  key: BILLING_SERVICE_URL
        volumeMounts:
          - name: config-volume
            mountPath: /app/config          
        livenessProbe:
          httpGet:
            port: 80
            path: /health
          initialDelaySeconds: 2
          periodSeconds: 5
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            port: 80
            path: /api/service/health
          initialDelaySeconds: 1
          periodSeconds: 5
          timeoutSeconds: 1
      volumes:
      - name: config-volume
        configMap:
          name: homework-config

--- 
### auth service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      initContainers:
        - name: check-db-ready
          image: postgres:latest
          env:
            - name: POSTGRES_HOST
              valueFrom:  
                configMapKeyRef: 
                  name: homework-config
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:  
                configMapKeyRef: 
                  name: homework-config
                  key: POSTGRES_PORT
          command:
            - sh
            - "-c"
            - |
              until pg_isready -h $POSTGRES_HOST -p $POSTGRES_PORT;
              do echo waiting for database; sleep 2; done;
      containers:
      - name: homeworkappauthservice
        image: alexcei88/otushomeworkauthservice
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"          
        ports:
          - containerPort: 80
        env:
          - name: "ConnectionStrings__DefaultConnection"
            valueFrom:
              secretKeyRef:
                name: homework-secret
                key: ESHOP_DATABASE_URI
          - name: "BillingService__Url"
            valueFrom:
               configMapKeyRef: 
                  name: homework-config
                  key: BILLING_SERVICE_URL
        volumeMounts:
          - name: config-volume
            mountPath: /app/config          
        livenessProbe:
          httpGet:
            port: 80
            path: /api/service/health
          initialDelaySeconds: 2
          periodSeconds: 5
          timeoutSeconds: 1
      volumes:
      - name: config-volume
        configMap:
          name: homework-config