apiVersion: v1
kind: Service
metadata:
  name: eshop-service
  labels:
    app: eshop
spec:
  selector:
    app: eshop
  ports:
  - port: 15020
    targetPort: 5020  
    name: "eshop-service"
  type: NodePort