### eshop api
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      initContainers:
        - name: check-db-ready
          image: postgres:latest
          env:
            - name: POSTGRES_HOST
              valueFrom:  
                configMapKeyRef: 
                  name: homework-config
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:  
                configMapKeyRef: 
                  name: homework-config
                  key: POSTGRES_PORT
            - name: "Smtp__Password"
              valueFrom:
               secretKeyRef: 
                  name: homework-secret
                  key: GMAIL_PASSWORD  
          command:
            - sh
            - "-c"
            - |
              until pg_isready -h $POSTGRES_HOST -p $POSTGRES_PORT;
              do echo waiting for database; sleep 2; done;
      containers:
      - name: notificationservice
        image: alexcei88/otushomeworknotificationservice
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"          
        ports:
          - containerPort: 5030
        env:
          - name: "ConnectionStrings__DefaultConnection"
            valueFrom:
              secretKeyRef:
                name: homework-secret
                key: NOTIFICATION_DATABASE_URI
        volumeMounts:
          - name: config-volume
            mountPath: /app/config          
        livenessProbe:
          httpGet:
            port: 5030
            path: /api/service/health
          initialDelaySeconds: 2
          periodSeconds: 5
          timeoutSeconds: 1
      volumes:
      - name: config-volume
        configMap:
          name: homework-config