apiVersion: apps/v1
kind: Deployment
metadata:
  name: pricing-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pricing
  template:
    metadata:
      labels:
        app: pricing
    spec:
      initContainers:
        - name: check-db-ready
          image: postgres:latest
          env:
            - name: POSTGRES_HOST
              valueFrom:  
                configMapKeyRef: 
                  name: homework-config
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:  
                configMapKeyRef: 
                  name: homework-config
                  key: POSTGRES_PORT
          command:
            - sh
            - "-c"
            - |
              until pg_isready -h $POSTGRES_HOST -p $POSTGRES_PORT;
              do echo waiting for database; sleep 2; done;
      containers:
      - name: pricingservice
        image: alexcei88/otushomeworkpricingservice
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"          
        ports:
          - containerPort: 5070
        env:
          - name: "ConnectionStrings__DefaultConnection"
            valueFrom:
              secretKeyRef:
                name: homework-secret
                key: PRICING_DATABASE_URI
          - name: "WarehouseService__Url"
            valueFrom:
               configMapKeyRef: 
                  name: homework-config
                  key: WAREHOUSE_SERVICE_URL
        volumeMounts:
          - name: config-volume
            mountPath: /app/config          
        livenessProbe:
          httpGet:
            port: 5070
            path: /api/service/health
          initialDelaySeconds: 2
          periodSeconds: 5
          timeoutSeconds: 1
      volumes:
      - name: config-volume
        configMap:
          name: homework-config