apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: eshop-servicemonitor
  labels:
    app: eshop
    release: prometheus
spec:
  namespaceSelector:
    any: true
  endpoints:
  - port: "eshop-service"
    path: /metrics
    interval: 7s
  selector:
    matchLabels:
      app: eshop