{
 "title": "OTUS homework API",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Ingress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latency (ms)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le)(rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])))*1000",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le)(rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])))*1000",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le)(rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])))*1000",
     "legendFormat": "0.99"
    },
    {
     "expr": "sum((rate(nginx_ingress_controller_request_duration_seconds_bucket{le=\"+Inf\"}[1m])))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_ingress_controller_nginx_process_requests_total[1m])",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "500 Error",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status)(rate(nginx_ingress_controller_request_duration_seconds_count{status=~\"5.+\"}[1m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  { "title": "Methods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Latency (ms)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le, method)(rate(request_duration_seconds_bucket[1m])))*1000",
     "legendFormat": "0.5 {{method}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le, method)(rate(request_duration_seconds_bucket[1m])))*1000",
     "legendFormat": "0.95 {{method}} "
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le, method)(rate(request_duration_seconds_bucket[1m])))*1000",
     "legendFormat": "0.99 {{method}}"
    },
    {
     "expr": "sum by (method)(rate(request_duration_seconds_bucket{le=\"+Inf\"}[1m]))*1000",
     "legendFormat": "max {{method}}"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(rate(total_requests[1m]))", "legendFormat": "RPS" }
   ]
  },
  {
   "title": "500 Error",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (method, status_code)(rate(request_duration_seconds_count{status_code=~\"5.+\"}[1m]))",
     "legendFormat": "{{method}}:{{status_code}}"
    }
   ]
  }
 ]
}