postgresqlUsername: postgres
postgresqlPassword: tc_123456
postgresqlDatabase: otus_eshop
fullnameOverride: postgres

service:
    type: NodePort
    port: 5432

persistence:
    enabled: true
    size: 1Gi

resources:
    requests:
        memory: 512Mi
        cpu: 200m