// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OTUS.HomeWork.Eshop.DAL;

namespace OTUS.HomeWork.EShop.Migrations
{
    [DbContext(typeof(OrderContext))]
    [Migration("20210327121010_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasPostgresExtension("uuid-ossp")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("OTUS.HomeWork.Eshop.Domain.Order", b =>
                {
                    b.Property<Guid>("OrderNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("order_number");

                    b.Property<string>("BillingId")
                        .HasColumnType("text")
                        .HasColumnName("billing_id");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<DateTime?>("PaidDateUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("paid_date_utc");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("total_price");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("OrderNumber")
                        .HasName("pk_orders");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("OTUS.HomeWork.Eshop.Domain.OrderItem", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid>("OrderNumberId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_number_id");

                    b.Property<Guid?>("OrderNumber1")
                        .HasColumnType("uuid")
                        .HasColumnName("order_number1");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("ProductId", "OrderNumberId")
                        .HasName("pk_order_item");

                    b.HasIndex("OrderNumber1")
                        .HasDatabaseName("ix_order_item_order_number1");

                    b.HasIndex("OrderNumberId")
                        .HasDatabaseName("ix_order_item_order_number_id");

                    b.ToTable("order_item");
                });

            modelBuilder.Entity("OTUS.HomeWork.Eshop.Domain.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9b52dbca-8b0b-4ab7-8dfa-0a5c994b2169"),
                            Description = "",
                            Name = "Футбольный Мяч",
                            Price = 100m
                        },
                        new
                        {
                            Id = new Guid("f3775353-956b-45c3-9c44-ed367439bdfe"),
                            Description = "",
                            Name = "Футбольная сетка",
                            Price = 400m
                        },
                        new
                        {
                            Id = new Guid("bfa42e50-b8d3-4500-b90c-4670f8754930"),
                            Description = "",
                            Name = "Футболка",
                            Price = 20m
                        },
                        new
                        {
                            Id = new Guid("c5d606b7-0deb-4da6-9cc5-e9f878adc165"),
                            Description = "",
                            Name = "Шорты",
                            Price = 20m
                        });
                });

            modelBuilder.Entity("OTUS.HomeWork.Eshop.Domain.OrderItem", b =>
                {
                    b.HasOne("OTUS.HomeWork.Eshop.Domain.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderNumber1")
                        .HasConstraintName("fk_order_item_orders_order_number1");

                    b.HasOne("OTUS.HomeWork.Eshop.Domain.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderNumberId")
                        .HasConstraintName("fk_order_item_orders_order_number")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("OTUS.HomeWork.Eshop.Domain.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
