// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OTUS.HomeWork.WarehouseService.DAL;

namespace OTUS.HomeWork.WarehouseService.Migrations
{
    [DbContext(typeof(WarehouseContext))]
    [Migration("20210516194844_addUserId")]
    partial class addUserId
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasPostgresExtension("uuid-ossp")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("OTUS.HomeWork.WarehouseService.Domain.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("numeric")
                        .HasColumnName("base_price");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<double>("Space")
                        .HasColumnType("double precision")
                        .HasColumnName("space");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("af438e30-c6c5-4b66-822f-5fe7c5466535"),
                            BasePrice = 100m,
                            Description = "",
                            Name = "Футбольный Мяч",
                            Space = 1.0,
                            Weight = 2.0
                        },
                        new
                        {
                            Id = new Guid("ef5ebaaa-0505-4fd9-9216-4bd596a877b3"),
                            BasePrice = 400m,
                            Description = "",
                            Name = "Футбольная сетка",
                            Space = 0.5,
                            Weight = 1.5
                        },
                        new
                        {
                            Id = new Guid("f6e1e19c-0ac0-47f1-b64e-ab7f2f1e3a8e"),
                            BasePrice = 20m,
                            Description = "",
                            Name = "Футболка",
                            Space = 0.10000000000000001,
                            Weight = 0.69999999999999996
                        },
                        new
                        {
                            Id = new Guid("876b7f79-dc25-45b6-ac0d-db8221ce9f96"),
                            BasePrice = 20m,
                            Description = "",
                            Name = "Шорты",
                            Space = 0.10000000000000001,
                            Weight = 0.40000000000000002
                        });
                });

            modelBuilder.Entity("OTUS.HomeWork.WarehouseService.Domain.ProductCounter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<long>("RemainCount")
                        .HasColumnType("bigint")
                        .HasColumnName("remain_count");

                    b.Property<long>("ReserveCount")
                        .HasColumnType("bigint")
                        .HasColumnName("reserve_count");

                    b.Property<long>("SoldCount")
                        .HasColumnType("bigint")
                        .HasColumnName("sold_count");

                    b.HasKey("Id")
                        .HasName("pk_counters");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_counters_product_id");

                    b.ToTable("counters");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8386d901-a049-4d64-b5c7-875bd342720f"),
                            ProductId = new Guid("af438e30-c6c5-4b66-822f-5fe7c5466535"),
                            RemainCount = 100L,
                            ReserveCount = 0L,
                            SoldCount = 0L
                        },
                        new
                        {
                            Id = new Guid("5de243bb-8ce6-459d-a441-0ceb8a274c10"),
                            ProductId = new Guid("ef5ebaaa-0505-4fd9-9216-4bd596a877b3"),
                            RemainCount = 50L,
                            ReserveCount = 0L,
                            SoldCount = 0L
                        },
                        new
                        {
                            Id = new Guid("b0ec6094-15a2-490b-8c5d-845aeb0c37b4"),
                            ProductId = new Guid("f6e1e19c-0ac0-47f1-b64e-ab7f2f1e3a8e"),
                            RemainCount = 20L,
                            ReserveCount = 4L,
                            SoldCount = 0L
                        },
                        new
                        {
                            Id = new Guid("08cb69c4-02a2-4729-9fc9-cc456eadec61"),
                            ProductId = new Guid("876b7f79-dc25-45b6-ac0d-db8221ce9f96"),
                            RemainCount = 25L,
                            ReserveCount = 1L,
                            SoldCount = 3L
                        });
                });

            modelBuilder.Entity("OTUS.HomeWork.WarehouseService.Domain.ReserveProduct", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("OrderNumber")
                        .HasColumnType("text")
                        .HasColumnName("order_number");

                    b.Property<long>("Count")
                        .HasColumnType("bigint")
                        .HasColumnName("count");

                    b.Property<DateTime>("ReserveDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("reserve_date");

                    b.HasKey("ProductId", "OrderNumber")
                        .HasName("pk_reserves");

                    b.ToTable("reserves");
                });

            modelBuilder.Entity("OTUS.HomeWork.WarehouseService.Domain.ShipmentOrder", b =>
                {
                    b.Property<string>("OrderNumber")
                        .HasColumnType("text")
                        .HasColumnName("order_number");

                    b.Property<string>("DeliveryAddress")
                        .HasColumnType("text")
                        .HasColumnName("delivery_address");

                    b.Property<string>("ErrorDescription")
                        .HasColumnType("text")
                        .HasColumnName("error_description");

                    b.Property<List<Guid>>("ProductIds")
                        .HasColumnType("uuid[]")
                        .HasColumnName("product_ids");

                    b.Property<DateTime>("ReadyToShipmentDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("ready_to_shipment_date");

                    b.Property<DateTime>("ShipmentDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("shipment_date");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<bool>("WasCancelled")
                        .HasColumnType("boolean")
                        .HasColumnName("was_cancelled");

                    b.HasKey("OrderNumber")
                        .HasName("pk_shipments");

                    b.ToTable("shipments");
                });

            modelBuilder.Entity("OTUS.HomeWork.WarehouseService.Domain.ProductCounter", b =>
                {
                    b.HasOne("OTUS.HomeWork.WarehouseService.Domain.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .HasConstraintName("fk_counters_products_product_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OTUS.HomeWork.WarehouseService.Domain.ReserveProduct", b =>
                {
                    b.HasOne("OTUS.HomeWork.WarehouseService.Domain.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .HasConstraintName("fk_reserves_products_product_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
