// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OTUS.HomeWork.WarehouseService.DAL;

namespace OTUS.HomeWork.WarehouseService.Migrations
{
    [DbContext(typeof(WarehouseContext))]
    [Migration("20210502180613_basePriceRename")]
    partial class basePriceRename
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasPostgresExtension("uuid-ossp")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("OTUS.HomeWork.WarehouseService.Domain.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("numeric")
                        .HasColumnName("base_price");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<double>("Space")
                        .HasColumnType("double precision")
                        .HasColumnName("space");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("faa58733-ae65-45aa-abbd-f48736b3c05d"),
                            BasePrice = 100m,
                            Description = "",
                            Name = "Футбольный Мяч",
                            Space = 1.0,
                            Weight = 2.0
                        },
                        new
                        {
                            Id = new Guid("0588b8df-a478-4c6a-ae5a-95bcc1935cc5"),
                            BasePrice = 400m,
                            Description = "",
                            Name = "Футбольная сетка",
                            Space = 0.5,
                            Weight = 1.5
                        },
                        new
                        {
                            Id = new Guid("da437b1f-f8b3-49e0-9057-6429155ac063"),
                            BasePrice = 20m,
                            Description = "",
                            Name = "Футболка",
                            Space = 0.10000000000000001,
                            Weight = 0.69999999999999996
                        },
                        new
                        {
                            Id = new Guid("97726a0b-f8ff-4911-a5c5-863028571afb"),
                            BasePrice = 20m,
                            Description = "",
                            Name = "Шорты",
                            Space = 0.10000000000000001,
                            Weight = 0.40000000000000002
                        });
                });

            modelBuilder.Entity("OTUS.HomeWork.WarehouseService.Domain.ProductCounter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<long>("RemainCount")
                        .HasColumnType("bigint")
                        .HasColumnName("remain_count");

                    b.Property<long>("ReserveCount")
                        .HasColumnType("bigint")
                        .HasColumnName("reserve_count");

                    b.Property<long>("SoldCount")
                        .HasColumnType("bigint")
                        .HasColumnName("sold_count");

                    b.HasKey("Id")
                        .HasName("pk_counters");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_counters_product_id");

                    b.ToTable("counters");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bb3f4b33-4d9b-4af9-aeaf-44d8e4f91b06"),
                            ProductId = new Guid("faa58733-ae65-45aa-abbd-f48736b3c05d"),
                            RemainCount = 10L,
                            ReserveCount = 0L,
                            SoldCount = 0L
                        },
                        new
                        {
                            Id = new Guid("51d386f4-919a-4f16-86b4-69d5a9da7a59"),
                            ProductId = new Guid("0588b8df-a478-4c6a-ae5a-95bcc1935cc5"),
                            RemainCount = 5L,
                            ReserveCount = 0L,
                            SoldCount = 0L
                        },
                        new
                        {
                            Id = new Guid("c2702386-05d3-45f5-a98e-a0f2ff7acb8b"),
                            ProductId = new Guid("da437b1f-f8b3-49e0-9057-6429155ac063"),
                            RemainCount = 10L,
                            ReserveCount = 4L,
                            SoldCount = 0L
                        },
                        new
                        {
                            Id = new Guid("b05d37e5-2ef2-439e-b14b-564bfa5f31da"),
                            ProductId = new Guid("97726a0b-f8ff-4911-a5c5-863028571afb"),
                            RemainCount = 5L,
                            ReserveCount = 1L,
                            SoldCount = 3L
                        });
                });

            modelBuilder.Entity("OTUS.HomeWork.WarehouseService.Domain.ReserveProduct", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("OrderNumber")
                        .HasColumnType("text")
                        .HasColumnName("order_number");

                    b.Property<long>("Count")
                        .HasColumnType("bigint")
                        .HasColumnName("count");

                    b.Property<DateTime>("ReserveDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("reserve_date");

                    b.HasKey("ProductId", "OrderNumber")
                        .HasName("pk_reserves");

                    b.ToTable("reserves");
                });

            modelBuilder.Entity("OTUS.HomeWork.WarehouseService.Domain.ShipmentOrder", b =>
                {
                    b.Property<string>("OrderNumber")
                        .HasColumnType("text")
                        .HasColumnName("order_number");

                    b.Property<string>("DeliveryAddress")
                        .HasColumnType("text")
                        .HasColumnName("delivery_address");

                    b.Property<List<Guid>>("ProductIds")
                        .HasColumnType("uuid[]")
                        .HasColumnName("product_ids");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("OrderNumber")
                        .HasName("pk_shipments");

                    b.ToTable("shipments");
                });

            modelBuilder.Entity("OTUS.HomeWork.WarehouseService.Domain.ProductCounter", b =>
                {
                    b.HasOne("OTUS.HomeWork.WarehouseService.Domain.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .HasConstraintName("fk_counters_products_product_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OTUS.HomeWork.WarehouseService.Domain.ReserveProduct", b =>
                {
                    b.HasOne("OTUS.HomeWork.WarehouseService.Domain.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .HasConstraintName("fk_reserves_products_product_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
